# Generated by Django 5.0 on 2024-01-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('system', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('machine', models.CharField(max_length=200)),
                ('architecture', models.CharField(max_length=200)),
                ('environment', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('sys_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.systeminformation')),
            ],
        ),
    ]
