# Generated by Django 5.0 on 2024-01-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_delete_systemdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.CharField(max_length=200)),
                ('CPU_USAGE', models.CharField(max_length=200)),
                ('CPU_FREQUENCY', models.CharField(max_length=200)),
                ('RAM', models.CharField(max_length=200)),
                ('HDD_TOTAL', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.CharField(max_length=200)),
                ('INFO1', models.CharField(max_length=200)),
                ('INFO2', models.CharField(max_length=200)),
                ('INFO3', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='systeminformation',
            old_name='architecture',
            new_name='ARCHITECTURE',
        ),
        migrations.RenameField(
            model_name='systeminformation',
            old_name='environment',
            new_name='ENVIRONMENT',
        ),
        migrations.RenameField(
            model_name='systeminformation',
            old_name='hostname',
            new_name='HOSTNAME',
        ),
        migrations.RenameField(
            model_name='systeminformation',
            old_name='machine',
            new_name='MACHINE',
        ),
        migrations.RenameField(
            model_name='systeminformation',
            old_name='processor',
            new_name='PROCESSOR',
        ),
        migrations.RenameField(
            model_name='systeminformation',
            old_name='system',
            new_name='SYSTEM',
        ),
        migrations.RenameField(
            model_name='systeminformation',
            old_name='user',
            new_name='USER',
        ),
        migrations.RenameField(
            model_name='systeminformation',
            old_name='version',
            new_name='VERSION',
        ),
    ]
