# Generated by Django 5.0 on 2024-01-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemData',
        ),
    ]
